---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
type: Opaque
stringData:
  DB: "mongodb://{{ .Values.mongodb.auth.reportsUsername }}:{{ .Values.mongodb.auth.reportsPassword }}@mongodb:27017/sausage-store"